# Generated by Django 3.1.3 on 2020-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201127_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
