# Generated by Django 3.1.3 on 2020-11-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201127_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sessions',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
