# Generated by Django 3.1.3 on 2020-11-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201127_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
