# Generated by Django 3.1.3 on 2020-11-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201127_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sessions',
        ),
    ]
